"""add completed_date to exercise_completions

Revision ID: 5658dd69d6de
Revises: 71b3a1219a02
Create Date: 2026-03-10 17:22:23.800161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5658dd69d6de'
down_revision: Union[str, None] = '71b3a1219a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_completions', sa.Column('completed_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_completions', 'completed_date')
    # ### end Alembic commands ###
