"""add cascade to related_guide_id

Revision ID: 71b3a1219a02
Revises: 9bc0f29f9ac3
Create Date: 2026-03-10 17:11:52.295727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b3a1219a02'
down_revision: Union[str, None] = '9bc0f29f9ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_sessions_related_guide_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'guide_results', ['related_guide_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_related_guide_id_fkey', 'chat_sessions', 'guide_results', ['related_guide_id'], ['id'])
    # ### end Alembic commands ###
