# chroniccare-frontend/nginx-frontend.conf
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React Router 새로고침 대응
    location / {
        try_files $uri $uri/ /index.html;
    }
}
